[pyprland]
plugins = [
  "scratchpads",
  "magnify"
]

[scratchpads.term]
animation = "fromTop"
margin = 10
force_monitor = "DP-3"
command = "kitty --class kitty-dropdown-term"
class = "kitty-dropdown-term"
size = "75% 60%"

[scratchpads.taskmon]
animation = "fromTop"
margin = 10
force_monitor = "DP-3"
command = "kitty --class kitty-dropdown-taskmon bpytop"
class = "kitty-dropdown-taskmon"
size = "75% 60%"
lazy = true

[scratchpads.gpumon]
animation = "fromTop"
margin = 10
force_monitor = "DP-3"
command = "kitty --class kitty-dropdown-btop radeontop"
class = "kitty-dropdown-gpumon"
size = "75% 60%"
lazy = true
