"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_macchiato"
format = """
[░▒▓](flamingo)\
$os\
[](bg:blue fg:flamingo)\
$directory\
[](fg:blue bg:mauve)\
$git_branch\
$git_status\
[](fg:mauve bg:surface0)\
$nodejs\
$rust\
$golang\
$dotnet\
$kubernetes\
[](surface0)\
$time\
\n$character"""
command_timeout = 3600

[character]
success_symbol = "[ ](fg:sky)"
error_symbol = "[ ](red)"
vicmd_symbol = "[ ](lavender)"

[os]
disabled = false
style = "bg:flamingo fg:crust bold"

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = " "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛"

[directory]
style = "fg:base bg:blue"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"
truncate_to_repo = false

# [directory.substitutions]
# "Documents" = "󰈙 "
# "Downloads" = " "
# "Music" = " "
# "Pictures" = " "
# "dev" = " "
# ".config" = " "
# "notes" = "󰏪 󰠮 "

[git_branch]
symbol = ""
style = "bg:mauve"
format = '[[ $symbol $branch ](fg:base bg:mauve)]($style)'

[git_status]
style = "bg:mauve"
format = '[[($ahead_behind)](fg:base bg:mauve)]($style)'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[nodejs]
symbol = ""
style = "bg:surface0"
format = '[[ $symbol ($version) ](fg:maroon bg:surface0)]($style)'

[rust]
symbol = ""
style = "bg:surface0"
format = '[[ $symbol ($version) ](fg:maroon bg:surface0)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:surface0"
format = '[[ $symbol ($version) ](fg:maroon bg:surface0)]($style)'

[dotnet]
symbol = "󱚣"
style = "bg:surface0"
format = '[[ $symbol ($version) ](fg:pink bg:surface0)]($style)'

[kubernetes]
symbol = "󱃾"
style = "bg:surface0"
format = '[[ $symbol ($version) ](fg:pink bg:surface0)]($style)'

[time]
disabled = false 
time_format = "%R" # Hour:Minute Format
style = "bg:base"
format = '[[  $time ](fg:overlay2 bg:base)]($style)'

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
